# Generated by Django 5.2.8 on 2025-11-30 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bean', '0002_alter_bean_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('deleted_when', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_when', models.DateTimeField(blank=True, null=True)),
                ('ended_when', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='These are overall notes the roaster may or may not want to add in about the overall roast', null=True)),
                ('bean', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roast', to='bean.bean')),
            ],
            options={
                'db_table': 'roast',
                'ordering': ['-created_when'],
            },
        ),
        migrations.CreateModel(
            name='RoastEvent',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('deleted_when', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_when', models.DateTimeField(blank=True, help_text='When the event tecnically started', null=True)),
                ('ended_when', models.DateTimeField(blank=True, help_text='When the even technically ended', null=True)),
                ('type', models.CharField(choices=[('pause', 'PAUSE'), ('dry_phase', 'DRY_PHASE'), ('first_crack', 'FIRST_CRACK'), ('second_crack', 'SECOND_CRACK')], max_length=255)),
                ('notes', models.TextField(blank=True, help_text='The roaster may or may not want to add in some information about the event', null=True)),
                ('roast', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roast_event', to='roast.roast')),
            ],
            options={
                'db_table': 'roast_event',
                'ordering': ['-created_when'],
            },
        ),
    ]
