# Generated by Django 5.2.8 on 2025-12-11 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('deleted_when', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_when', models.DateTimeField(blank=True, null=True)),
                ('ended_when', models.DateTimeField(blank=True, null=True)),
                ('target_duration', models.DurationField(blank=True, help_text='This is a timestamp to represent the target amount of time from start to end (when they would like to stop the roast)', null=True)),
                ('target_when', models.DateTimeField(blank=True, help_text='In correspondance with target_duration we just want the end time in plain timestamp format without having to do a bunch of math.  Easier to do it server side', null=True)),
                ('notes', models.TextField(blank=True, help_text='These are overall notes the roaster may or may not want to add in about the overall roast', null=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roasts', to='bean.bean')),
            ],
            options={
                'db_table': 'roasts',
                'ordering': ['-created_when'],
            },
        ),
        migrations.CreateModel(
            name='RoastEvent',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('deleted_when', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_when', models.DateTimeField(blank=True, help_text='When the event tecnically started', null=True)),
                ('ended_when', models.DateTimeField(blank=True, help_text='When the even technically ended', null=True)),
                ('type', models.CharField(choices=[('begin', 'BEGIN'), ('note', 'NOTE'), ('dry_phase', 'DRY_PHASE'), ('first_crack', 'FIRST_CRACK'), ('second_crack', 'SECOND_CRACK'), ('drop', 'DROP')], max_length=255)),
                ('notes', models.TextField(blank=True, help_text='The roaster may or may not want to add in some information about the event', null=True)),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_event', to='roast.roast')),
            ],
            options={
                'db_table': 'roast_events',
                'ordering': ['-created_when'],
            },
        ),
    ]
