# Generated by Django 5.2.8 on 2025-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='target_when',
            field=models.DateTimeField(blank=True, help_text='This is a timestamp to represent the target amount of time from start to end (when they would like to stop the roast)', null=True),
        ),
    ]
