# Generated by Django 6.0 on 2025-12-17 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastProfile',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('deleted_when', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flavors', models.JSONField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='roast.roast')),
            ],
            options={
                'db_table': 'roast_profiles',
            },
        ),
    ]
