# Generated by Django 6.0 on 2025-12-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0002_roastprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roastevent',
            name='ended_when',
        ),
        migrations.RemoveField(
            model_name='roastevent',
            name='started_when',
        ),
        migrations.AlterField(
            model_name='roastevent',
            name='type',
            field=models.CharField(choices=[('begin', 'BEGIN'), ('note', 'NOTE'), ('dry_phase_start', 'DRY_PHASE_START'), ('dry_phase_end', 'DRY_PHASE_END'), ('first_crack', 'FIRST_CRACK'), ('second_crack', 'SECOND_CRACK'), ('emergency_stop', 'EMERGENCY_STOP'), ('drop', 'DROP'), ('cooling_start', 'COOLING_START'), ('cooling_stop', 'COOLING_STOP')], max_length=255),
        ),
        migrations.AlterField(
            model_name='roastprofile',
            name='roast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_profile', to='roast.roast'),
        ),
    ]
