# Generated by Django 6.0 on 2025-12-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0002_roastprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roastevent',
            name='ended_when',
        ),
        migrations.RemoveField(
            model_name='roastevent',
            name='started_when',
        ),
        migrations.AlterField(
            model_name='roastevent',
            name='type',
            field=models.CharField(choices=[('begin', 'BEGIN'), ('note', 'NOTE'), ('dry_phase', 'DRY_PHASE'), ('first_crack', 'FIRST_CRACK'), ('second_crack', 'SECOND_CRACK'), ('emergency_stop', 'EMERGENCY_STOP'), ('drop', 'DROP'), ('cooling_start', 'COOLING_START'), ('cooling_stop', 'COOLING_STOP')], max_length=255),
        ),
    ]
