# Generated by Django 6.0 on 2026-01-15 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0003_remove_roastevent_ended_when_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roastprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('light', 'LIGHT'), ('medium', 'MEDIUM'), ('dark', 'DARK')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roastprofile',
            name='smell',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roastprofile',
            name='roast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roast_profile', to='roast.roast'),
        ),
    ]
