# Generated by Django 6.0 on 2026-01-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0004_roastprofile_level_roastprofile_smell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='target_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
