# Generated by Django 6.0 on 2026-01-18 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0005_roast_target_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastFlavors',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('deleted_when', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'roast_flavors',
            },
        ),
        migrations.RemoveField(
            model_name='roastprofile',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='roastprofile',
            name='flavors',
        ),
        migrations.RemoveField(
            model_name='roastprofile',
            name='smell',
        ),
        migrations.CreateModel(
            name='RoastProfileFlavors',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('deleted_when', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scale', models.PositiveSmallIntegerField(default=50, help_text='Provides a scale from 1-100 of how much of a certain flavor is detected in a roast profile.')),
                ('roast_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_flavors', to='roast.roastflavors')),
                ('roast_profile', models.ManyToManyField(db_table='roast_profile_to_flavors', related_name='roast_profile_flavors', to='roast.roastprofile')),
            ],
            options={
                'db_table': 'roast_profile_flavors',
            },
        ),
    ]
