# Generated by Django 6.0 on 2026-01-18 22:58

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def apply_migration(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Add defaults into the table, I think the approach I'd like to take
    is to just allow these things to be managed via settings.
    """
    RoastFlavor = apps.get_model("roast", "RoastFlavors")
    defaults = ["spicy", "chocolatey", "nutty", "buttery", "fruity", "flowery", "winey", "earthy"]
    roast_flavors_to_create = []
    for default in defaults:
        roast_flavor = RoastFlavor()
        roast_flavor.name = default
        roast_flavors_to_create.append(roast_flavor)
    RoastFlavor.objects.bulk_create(roast_flavors_to_create)


def reverse_migration(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Reverse the table defaults and remove the data (if need be).
    """
    RoastFlavor = apps.get_model("roast", "RoastFlavors")
    RoastFlavor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("roast", "0006_remove_roastprofile_attributes_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=apply_migration,
            reverse_code=reverse_migration,
        )
    ]
