# Generated by Django 5.2.8 on 2025-12-11 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('deleted_when', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The name of the origin of the bean.', max_length=255, null=True)),
                ('sca_grade', models.IntegerField(blank=True, help_text='Uses the Specialty Coffee Association grade system to score the quality', null=True)),
                ('sca_letter_grade', models.CharField(blank=True, choices=[('G1', 'SPECIALTY_GRADE'), ('G2', 'PREMIUM_GRADE'), ('G3', 'COMMERCIAL_GRADE')], max_length=255, null=True)),
                ('processing', models.CharField(blank=True, choices=[('washed', 'WASHED'), ('natural', 'NATURAL'), ('honey', 'HONEY')], max_length=255, null=True)),
                ('origin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='origin.origin')),
            ],
            options={
                'db_table': 'beans',
                'ordering': ['-created_when'],
            },
        ),
    ]
