# Generated by Django 6.0 on 2026-01-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
