# Generated by Django 5.2.8 on 2025-11-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bean', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bean',
            options={'ordering': ['-created_when']},
        ),
    ]
