# Generated by Django 5.2.8 on 2025-12-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origin',
            options={'ordering': ['-created_when']},
        ),
    ]
